// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const FontInter = Inter({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
//   });

const poppins = Poppins({
  weight: ["400", '500', '600', '700'],
  subsets: ['latin'],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-gray-900 text-gray-50 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
